github: add release drafter, mode deploy.sh into workflow (#1)

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -1,9 +1,8 @@
 name: Docker
 
 on:
-  push:
-    branches:
-      - master
+  release:
+    types: [released]
 
 env:
   IMAGE_NAME: cli-tools
@@ -18,7 +17,18 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Build image
-        run: ./deploy.sh
+        run: |
+            if [ -f versions ]; then
+              export $(grep -v '^#' versions | xargs)
+              ./build.sh \
+                DOCKER_TAG=${GITHUB_REF#refs/*/} \
+                VERSION_HELM=$VERSION_HELM \
+                VERSION_KUBECTL=$VERSION_KUBECTL \
+                VERSION_TERRAFORM=$VERSION_TERRAFORM
+            else
+              echo "Error: Could not find the versions file!"
+              exit 2
+            fi
 
       - name: Log into registry
         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
@@ -26,23 +36,20 @@ jobs:
       - name: Push image
         run: docker push docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
 
-  slack-notification:
-    runs-on: ubuntu-latest
-    needs: docker-build-push
-    name: Send message to slack channel if docker push completed
+  # slack-notification:
+  #   runs-on: ubuntu-latest
+  #   needs: docker-build-push
+  #   name: Send message to slack channel if docker push completed
 
-    steps:
-      - uses: actions/checkout@v2
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Grab latest version for slack message
-        run:  echo "::set-env name=DOCKER_TAG::$(cat versions | grep DOCKER_TAG= | head -n 1 | grep -o '".*"' | sed 's/"//g')"
+  #     - name: Send message to Slack API
+  #       uses: archive/github-actions-slack@v1.0.2
+  #       with:
+  #         slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
+  #         slack-channel: internal-releases
+  #         slack-text: "cli-tools updated, the latest version is now ${GITHUB_REF#refs/*/}. :bongo:"
 
-      - name: Send message to Slack API
-        uses: archive/github-actions-slack@v1.0.2
-        with:
-          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
-          slack-channel: team-cloud
-          slack-text: "cli-tools updated, the latest version is now ${{ env.DOCKER_TAG }}. Time for a docker pull team-cloud :bongo:"
-
-      - name: Result from "Send Message"
-        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
+  #     - name: Result from "Send Message"
+  #       run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
